### ISSUE TITLE
Requirement pyegsphsp not  matching

### ISSUE THREAD

**Issue by blenisgil** [henrybaxter/pyegsphsp#2]
Dear Henry Baxter,
My name is Bladimir Lenis, student of Master in Medical Physics. I am writing to you because I have tried to use your repository (pyegsphsp) to read and write Phase Space Files (* .egsphsp#) with Python, however when installing the repository with pip the following error always occurs:
-_Could not find a version that satisfies the requirement pyegsphsp (from versions:) No matching distribution found for pyegsphsp._

I have used pip19.0.1 and different versions of python (2.7, 3.7 and 3.5)
![2019-02-02-133023_1280x800_scrot](https://user-images.githubusercontent.com/45550922/52169478-1b6ea080-2707-11e9-856f-025a7ba30ad6.png)

Do you know why this error is generated?
I attach a photo
Thanks!

Best regards, Bladimir
blenis1@uc.cl

**Comment by henrybaxter** [comment]
Hi Bladimir, I am so sorry I did not get back to you sooner, I would be curious to know how your research is going and if you were able to get this working. Happy to help if you're still working in that area!

Take care

**Comment by blenisgil** [comment]
Hi Henry,

I appreciate your disposition, however, based on your python code, I made my own code in matlab to read and write egsphsp# files.

Thank you very much

Best regards, Bladimir

**Comment by henrybaxter** [comment]
Ok fantastic, sorry it didn't work at the time for you. Take care!
